version: '3.8'  
  
services:    
  frontend:  
    build: ./client  
    container_name: chronogaz_frontend  
    restart: unless-stopped  
    ports:  
      - "3001:3000"  
    volumes:  
      - ./client:/app  
      - /app/node_modules  
    environment:  
      - CHOKIDAR_USEPOLLING=true